[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "astron-result",
]

[tool.uv.sources]
astron-result = { git = "https://github.com/ASTRON-AI/astron-result.git" }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
